import {mkdirSync, writeFileSync} from "node:fs";
import path from "node:path";
import {siteConfig} from "../src/lib/seo";
import {newsItems} from "../src/store/staticNews";

const OUTPUT_DIR = path.resolve(process.cwd(), ".sitemap");
const BANNER = "// Auto-generated by scripts/generate-sitemap-data.ts. Do not edit manually.\n";

const writeModule = (fileName: string, exportName: string, value: unknown) => {
    mkdirSync(OUTPUT_DIR, {recursive: true});
    const filePath = path.join(OUTPUT_DIR, fileName);
    const serialized = JSON.stringify(value, null, 2);
    const contents = `${BANNER}module.exports = { ${exportName}: ${serialized} };\n`;
    writeFileSync(filePath, contents, "utf8");
};

writeModule("siteConfig.cjs", "siteConfig", siteConfig);
writeModule("newsItems.cjs", "newsItems", newsItems);
